"""add totp recovery codes

Revision ID: 134db5e62c28
Revises: e68569e42d32
Create Date: 2026-08-09 08:00:37.356104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134db5e62c28'
down_revision: Union[str, None] = 'e68569e42d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totp_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=256), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('totp_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_totp_recovery_codes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_totp_recovery_codes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('totp_recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_totp_recovery_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_totp_recovery_codes_id'))

    op.drop_table('totp_recovery_codes')
    # ### end Alembic commands ###
