"""initial schema

Revision ID: 5671732de8f7
Revises: 
Create Date: 2026-08-02 16:29:20.227363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5671732de8f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('target_steam_id', sa.String(length=32), nullable=True),
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('character_name', sa.String(length=64), nullable=False),
    sa.Column('admin_name', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=False),
    sa.Column('unban_at', sa.DateTime(), nullable=True),
    sa.Column('unbanned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bans_id'), 'bans', ['id'], unique=False)
    op.create_index(op.f('ix_bans_steam_id'), 'bans', ['steam_id'], unique=False)
    op.create_table('clans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('tag', sa.String(length=6), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clans_id'), 'clans', ['id'], unique=False)
    op.create_index(op.f('ix_clans_name'), 'clans', ['name'], unique=True)
    op.create_index(op.f('ix_clans_tag'), 'clans', ['tag'], unique=True)
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_error_logs_date', 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_id'), 'error_logs', ['id'], unique=False)
    op.create_table('game_clans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('clan_guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('motto', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_num', 'clan_guid', name='uq_game_clan_server_guid')
    )
    op.create_index(op.f('ix_game_clans_clan_guid'), 'game_clans', ['clan_guid'], unique=False)
    op.create_index(op.f('ix_game_clans_id'), 'game_clans', ['id'], unique=False)
    op.create_table('moderation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('admin_name', sa.String(length=64), nullable=True),
    sa.Column('target_name', sa.String(length=64), nullable=True),
    sa.Column('target_steam_id', sa.String(length=32), nullable=True),
    sa.Column('details', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_log_created', 'moderation_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderation_log_id'), 'moderation_log', ['id'], unique=False)
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_page_views_date', 'page_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_page_views_id'), 'page_views', ['id'], unique=False)
    op.create_table('player_daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('activity_date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_num', 'steam_id', 'activity_date', name='uq_player_daily_activity')
    )
    op.create_index(op.f('ix_player_daily_activity_id'), 'player_daily_activity', ['id'], unique=False)
    op.create_index(op.f('ix_player_daily_activity_steam_id'), 'player_daily_activity', ['steam_id'], unique=False)
    op.create_table('player_rank_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=128), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_rank_snapshots_id'), 'player_rank_snapshots', ['id'], unique=False)
    op.create_index('ix_rank_snap_server_player_time', 'player_rank_snapshots', ['server_num', 'player_name', 'recorded_at'], unique=False)
    op.create_table('player_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=128), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_duration', sa.Integer(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_num', 'player_name', name='uq_player_server')
    )
    op.create_index(op.f('ix_player_records_id'), 'player_records', ['id'], unique=False)
    op.create_index(op.f('ix_player_records_steam_id'), 'player_records', ['steam_id'], unique=False)
    op.create_table('plugin_heartbeats',
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(length=128), nullable=True),
    sa.Column('plugin_version', sa.String(length=32), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('server_num')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_id'), 'revoked_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=True)
    op.create_table('scheduled_restarts',
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('restart_at', sa.DateTime(), nullable=True),
    sa.Column('daily_restart_time', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('server_num')
    )
    op.create_table('server_api_keys',
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('server_num')
    )
    op.create_table('server_message_templates',
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('connect_template', sa.Text(), nullable=True),
    sa.Column('disconnect_template', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('server_num')
    )
    op.create_table('server_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('map_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_snapshots_id'), 'server_snapshots', ['id'], unique=False)
    op.create_index('ix_snapshots_server_time', 'server_snapshots', ['server_num', 'recorded_at'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_items_id'), 'shop_items', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('rules_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('game_nickname', sa.String(length=64), nullable=True),
    sa.Column('admin_title', sa.String(length=128), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('badge_icon_url', sa.String(length=512), nullable=True),
    sa.Column('badge_style', sa.String(length=32), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('bio', sa.String(length=160), nullable=True),
    sa.Column('steam_id', sa.String(length=32), nullable=True),
    sa.Column('revoke_before', sa.DateTime(), nullable=True),
    sa.Column('points_balance', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_steam_id'), 'users', ['steam_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('warn_escalation_state',
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('last_escalation_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.create_table('warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('character_name', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('admin_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warnings_id'), 'warnings', ['id'], unique=False)
    op.create_index(op.f('ix_warnings_steam_id'), 'warnings', ['steam_id'], unique=False)
    op.create_table('wipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_num', sa.Integer(), nullable=False),
    sa.Column('wipe_type', sa.String(length=32), nullable=False),
    sa.Column('wipe_date', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wipes_id'), 'wipes', ['id'], unique=False)
    op.create_table('ban_appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ban_id', sa.Integer(), nullable=True),
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('character_name', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('admin_response', sa.String(length=1024), nullable=True),
    sa.Column('admin_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ban_id'], ['bans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ban_appeals_id'), 'ban_appeals', ['id'], unique=False)
    op.create_index(op.f('ix_ban_appeals_steam_id'), 'ban_appeals', ['steam_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('game_clan_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('floor_count', sa.Integer(), nullable=False),
    sa.Column('is_raid_protected', sa.Boolean(), nullable=False),
    sa.Column('min_x', sa.Integer(), nullable=False),
    sa.Column('min_z', sa.Integer(), nullable=False),
    sa.Column('max_x', sa.Integer(), nullable=False),
    sa.Column('max_z', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['game_clans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_clan_bases_clan', 'game_clan_bases', ['clan_id'], unique=False)
    op.create_index(op.f('ix_game_clan_bases_id'), 'game_clan_bases', ['id'], unique=False)
    op.create_table('game_clan_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('character_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_connected_unix', sa.Integer(), nullable=True),
    sa.Column('physical_power', sa.Float(), nullable=True),
    sa.Column('spell_power', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['game_clans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_clan_members_clan', 'game_clan_members', ['clan_id'], unique=False)
    op.create_index(op.f('ix_game_clan_members_id'), 'game_clan_members', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_index(op.f('ix_news_slug'), 'news', ['slug'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_user', 'notifications', ['user_id', 'read'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_id'), 'password_resets', ['id'], unique=False)
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    op.create_table('points_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=256), nullable=True),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_transactions_id'), 'points_transactions', ['id'], unique=False)
    op.create_index('ix_points_transactions_user', 'points_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('shop_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=True),
    sa.Column('item_name_snapshot', sa.String(length=128), nullable=False),
    sa.Column('cost_snapshot', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('delivery_mode', sa.String(length=16), nullable=False),
    sa.Column('player_note', sa.String(length=500), nullable=True),
    sa.Column('admin_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_redemptions_id'), 'shop_redemptions', ['id'], unique=False)
    op.create_index('ix_shop_redemptions_status_created', 'shop_redemptions', ['status', 'created_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index('ix_comments_news_id', 'comments', ['news_id'], unique=False)
    op.create_table('event_participants',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=256), nullable=False),
    sa.Column('multiple', sa.Boolean(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_id'), 'polls', ['id'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', 'user_id', 'emoji', name='uq_reaction')
    )
    op.create_index(op.f('ix_reactions_id'), 'reactions', ['id'], unique=False)
    op.create_table('comment_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', 'emoji', name='uq_comment_reaction')
    )
    op.create_index(op.f('ix_comment_reactions_id'), 'comment_reactions', ['id'], unique=False)
    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_options_id'), 'poll_options', ['id'], unique=False)
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id', name='uq_poll_vote')
    )
    op.create_index(op.f('ix_poll_votes_id'), 'poll_votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poll_votes_id'), table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index(op.f('ix_poll_options_id'), table_name='poll_options')
    op.drop_table('poll_options')
    op.drop_index(op.f('ix_comment_reactions_id'), table_name='comment_reactions')
    op.drop_table('comment_reactions')
    op.drop_index(op.f('ix_reactions_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_polls_id'), table_name='polls')
    op.drop_table('polls')
    op.drop_table('event_participants')
    op.drop_index('ix_comments_news_id', table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_shop_redemptions_status_created', table_name='shop_redemptions')
    op.drop_index(op.f('ix_shop_redemptions_id'), table_name='shop_redemptions')
    op.drop_table('shop_redemptions')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_points_transactions_user', table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_id'), table_name='points_transactions')
    op.drop_table('points_transactions')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_id'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index('ix_notifications_user', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_game_clan_members_id'), table_name='game_clan_members')
    op.drop_index('ix_game_clan_members_clan', table_name='game_clan_members')
    op.drop_table('game_clan_members')
    op.drop_index(op.f('ix_game_clan_bases_id'), table_name='game_clan_bases')
    op.drop_index('ix_game_clan_bases_clan', table_name='game_clan_bases')
    op.drop_table('game_clan_bases')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_ban_appeals_steam_id'), table_name='ban_appeals')
    op.drop_index(op.f('ix_ban_appeals_id'), table_name='ban_appeals')
    op.drop_table('ban_appeals')
    op.drop_index(op.f('ix_wipes_id'), table_name='wipes')
    op.drop_table('wipes')
    op.drop_index(op.f('ix_warnings_steam_id'), table_name='warnings')
    op.drop_index(op.f('ix_warnings_id'), table_name='warnings')
    op.drop_table('warnings')
    op.drop_table('warn_escalation_state')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_steam_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shop_items_id'), table_name='shop_items')
    op.drop_table('shop_items')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index('ix_snapshots_server_time', table_name='server_snapshots')
    op.drop_index(op.f('ix_server_snapshots_id'), table_name='server_snapshots')
    op.drop_table('server_snapshots')
    op.drop_table('server_message_templates')
    op.drop_table('server_api_keys')
    op.drop_table('scheduled_restarts')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_id'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_table('plugin_heartbeats')
    op.drop_index(op.f('ix_player_records_steam_id'), table_name='player_records')
    op.drop_index(op.f('ix_player_records_id'), table_name='player_records')
    op.drop_table('player_records')
    op.drop_index('ix_rank_snap_server_player_time', table_name='player_rank_snapshots')
    op.drop_index(op.f('ix_player_rank_snapshots_id'), table_name='player_rank_snapshots')
    op.drop_table('player_rank_snapshots')
    op.drop_index(op.f('ix_player_daily_activity_steam_id'), table_name='player_daily_activity')
    op.drop_index(op.f('ix_player_daily_activity_id'), table_name='player_daily_activity')
    op.drop_table('player_daily_activity')
    op.drop_index(op.f('ix_page_views_id'), table_name='page_views')
    op.drop_index('ix_page_views_date', table_name='page_views')
    op.drop_table('page_views')
    op.drop_index(op.f('ix_moderation_log_id'), table_name='moderation_log')
    op.drop_index('ix_moderation_log_created', table_name='moderation_log')
    op.drop_table('moderation_log')
    op.drop_index(op.f('ix_game_clans_id'), table_name='game_clans')
    op.drop_index(op.f('ix_game_clans_clan_guid'), table_name='game_clans')
    op.drop_table('game_clans')
    op.drop_index(op.f('ix_error_logs_id'), table_name='error_logs')
    op.drop_index('ix_error_logs_date', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_clans_tag'), table_name='clans')
    op.drop_index(op.f('ix_clans_name'), table_name='clans')
    op.drop_index(op.f('ix_clans_id'), table_name='clans')
    op.drop_table('clans')
    op.drop_index(op.f('ix_bans_steam_id'), table_name='bans')
    op.drop_index(op.f('ix_bans_id'), table_name='bans')
    op.drop_table('bans')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
