"""add auto_flag_rules table

Revision ID: a546dcd125f8
Revises: e68569e42d32
Create Date: 2026-08-09 08:05:07.861701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a546dcd125f8'
down_revision: Union[str, None] = 'e68569e42d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_flag_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_flag_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auto_flag_rules_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_flag_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auto_flag_rules_id'))

    op.drop_table('auto_flag_rules')
    # ### end Alembic commands ###
