"""add message attachment and reply_to columns

Revision ID: ce2f72416a1e
Revises: a546dcd125f8
Create Date: 2026-08-09 13:35:06.730850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2f72416a1e'
down_revision: Union[str, None] = 'a546dcd125f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate emitted an unnamed create_foreign_key(None, ...) here, which SQLite's
    # batch mode (this repo runs render_as_batch=True unconditionally — see env.py)
    # rejects outright ("Constraint must have a name") since the copy-to-new-table
    # rebuild needs something to refer to — named explicitly below, and the downgrade's
    # drop_constraint(...) updated to match rather than relying on the unnamed `None`
    # autogenerate also produced there.
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_foreign_key('fk_messages_reply_to_id_messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_reply_to_id_messages', type_='foreignkey')
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('reply_to_id')
        batch_op.drop_column('attachment_url')

    # ### end Alembic commands ###
