"""add shop item category, weekly limit, wishlist

Revision ID: e44508fdf945
Revises: e68569e42d32
Create Date: 2026-08-09 08:01:24.248080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44508fdf945'
down_revision: Union[str, None] = 'e68569e42d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shop_item_id', name='uq_shop_wishlist_user_item')
    )
    with op.batch_alter_table('shop_wishlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_wishlist_items_id'), ['id'], unique=False)

    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('weekly_limit_per_user', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.drop_column('weekly_limit_per_user')
        batch_op.drop_column('category')

    with op.batch_alter_table('shop_wishlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_wishlist_items_id'))

    op.drop_table('shop_wishlist_items')
    # ### end Alembic commands ###
