"""add leaderboard/comment/notification composite indexes

Revision ID: e68569e42d32
Revises: 8764c40cd0a9
Create Date: 2026-08-09 07:21:18.443576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68569e42d32'
down_revision: Union[str, None] = '8764c40cd0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('ix_comments_news_id_created', ['news_id', 'created_at'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('player_records', schema=None) as batch_op:
        batch_op.create_index('ix_player_records_server_lastseen', ['server_num', 'last_seen'], unique=False)
        batch_op.create_index('ix_player_records_server_seconds', ['server_num', 'total_seconds'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_records', schema=None) as batch_op:
        batch_op.drop_index('ix_player_records_server_seconds')
        batch_op.drop_index('ix_player_records_server_lastseen')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_created')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comments_news_id_created')

    # ### end Alembic commands ###
