"""sync with current models

Revision ID: f601e6a00586
Revises: 5671732de8f7
Create Date: 2026-08-05 12:35:58.591951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f601e6a00586'
down_revision: Union[str, None] = '5671732de8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_poll_vote'), type_='unique')
        batch_op.create_unique_constraint('uq_poll_vote', ['poll_id', 'option_id', 'user_id'])
        batch_op.create_index(batch_op.f('ix_poll_votes_option_id'), ['option_id'], unique=False)

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_polls_news_id'), ['news_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_polls_news_id'))

    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_votes_option_id'))
        batch_op.drop_constraint('uq_poll_vote', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_poll_vote'), ['poll_id', 'user_id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_author_id'))

    # ### end Alembic commands ###
